### ISSUE TITLE
Add internationalisation

### ISSUE THREAD

**Issue by catileptic** [code4romania/date-la-zi#152]
- [ ] Add internationalisation (feature)
- [ ] Add language switch to nav bar
- [ ] Translate all texts / tags

**Comment by lorenabalan** [comment]
Under this umbrella, is it worth making Last Updated date be in local timezone, as opposed to Ro timezone?
![Screenshot 2020-04-04 at 18 08 25](https://user-images.githubusercontent.com/6642900/78457041-566bbb80-769f-11ea-9080-c95c2f2170b1.png)

Found it a little confusing when checking the dashboard from abroad, assuming it's because of [this line](https://github.com/code4romania/date-la-zi/blob/d2eb1c41dc971ec85aa1334d28d373104f3bd7f1/frontend/src/utils/date.js#L2). Happy to create a separate issue if it makes more sense.

**Comment by tudorgergely** [comment]
@catileptic is this still relevant? I saw the PR hasn’t been updated in a while

**Comment by Utwo** [comment]
I think we can close this
